version: '3.8'

services:
  webex-bot:
    build: .
    container_name: webex_repo_man_bot
    ports:
      - "5000:5000"
    volumes:
      # Mount the entire project directory into the container.
      # This allows for live-reloading of code during development.
      # Any change on the host machine will be immediately reflected in the container.
      - .:/usr/src/app
      # Persist the database file
      - webex_bot_data:/usr/src/app/app/webex-bot.db
    environment:
      - FLASK_APP=run.py
    command: >
      sh -c "flask db upgrade &&
             python run.py"
    restart: unless-stopped

volumes:
  webex_bot_data:

